// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Resume_NCDL.Data;

#nullable disable

namespace Resume_NCDL.Migrations
{
    [DbContext(typeof(ApplicationdbContext))]
    [Migration("20260422115628_AddAnalysisSessionsAndResults")]
    partial class AddAnalysisSessionsAndResults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Resume_NCDL.Models.AnalysisResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AffindaAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("CandidateType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CareerBreak")
                        .HasColumnType("bit");

                    b.Property<string>("CareerBreakDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyCount")
                        .HasColumnType("int");

                    b.Property<bool>("CompanyCountEstimated")
                        .HasColumnType("bit");

                    b.Property<double>("DisplayScore")
                        .HasColumnType("float");

                    b.Property<string>("Domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DomainMismatch")
                        .HasColumnType("bit");

                    b.Property<bool>("DomainSwitch")
                        .HasColumnType("bit");

                    b.Property<string>("DomainSwitchFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Education")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmploymentGap")
                        .HasColumnType("bit");

                    b.Property<string>("EmploymentGapDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Experience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ExperienceYears")
                        .HasColumnType("float");

                    b.Property<string>("Internship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JdDomain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatchedSkillsCsv")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("MissingSkillsCsv")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NearMiss")
                        .HasColumnType("bit");

                    b.Property<string>("NearMissDetail")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("NotMatchedFeedback")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Projects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RawScore")
                        .HasColumnType("float");

                    b.Property<string>("SavedFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ScoreSuppressed")
                        .HasColumnType("bit");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("SkillCoveragePct")
                        .HasColumnType("int");

                    b.Property<string>("SkillGapDetail")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StayingLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Tier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TierDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalJdSkills")
                        .HasColumnType("int");

                    b.Property<string>("WorkLocations")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("AnalysisResults", (string)null);
                });

            modelBuilder.Entity("Resume_NCDL.Models.AnalysisSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DomainMismatchCount")
                        .HasColumnType("int");

                    b.Property<string>("JdText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MatchedCount")
                        .HasColumnType("int");

                    b.Property<int>("NearMissCount")
                        .HasColumnType("int");

                    b.Property<int>("NotMatchedCount")
                        .HasColumnType("int");

                    b.Property<int>("Threshold")
                        .HasColumnType("int");

                    b.Property<int>("TotalResumes")
                        .HasColumnType("int");

                    b.Property<string>("TriggeredBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AnalysisSessions", (string)null);
                });

            modelBuilder.Entity("Resume_NCDL.Models.Details", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ResumeContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ResumeData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ResumeFileName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InfoTable");
                });

            modelBuilder.Entity("Resume_NCDL.Models.AnalysisResult", b =>
                {
                    b.HasOne("Resume_NCDL.Models.AnalysisSession", "Session")
                        .WithMany("Results")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Resume_NCDL.Models.AnalysisSession", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
