// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Resume_NCDL.Data;

#nullable disable

namespace Resume_NCDL.Migrations
{
    [DbContext(typeof(ApplicationdbContext))]
    [Migration("20260422130705_AddResult")]
    partial class AddResult
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Resume_NCDL.Models.Details", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ResumeContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ResumeData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ResumeFileName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InfoTable");
                });

            modelBuilder.Entity("Resume_NCDL.Models.ResumeMatchResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CandidateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CandidateType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CareerBreak")
                        .HasColumnType("bit");

                    b.Property<string>("CareerBreakDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyCount")
                        .HasColumnType("int");

                    b.Property<double>("DisplayScore")
                        .HasColumnType("float");

                    b.Property<string>("Domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DomainMismatch")
                        .HasColumnType("bit");

                    b.Property<bool>("DomainSwitch")
                        .HasColumnType("bit");

                    b.Property<string>("DomainSwitchFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Education")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmploymentGap")
                        .HasColumnType("bit");

                    b.Property<string>("EmploymentGapDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ExpYears")
                        .HasColumnType("float");

                    b.Property<string>("Experience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Internship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsScoreSuppressed")
                        .HasColumnType("bit");

                    b.Property<string>("JdDomain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JdSnippet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatchedSkills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MissingSkills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NearMiss")
                        .HasColumnType("bit");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Projects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RawScore")
                        .HasColumnType("float");

                    b.Property<string>("SavedFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillCoveragePct")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StayingLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Threshold")
                        .HasColumnType("int");

                    b.Property<string>("Tier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TierDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalJdSkills")
                        .HasColumnType("int");

                    b.Property<string>("WorkLocations")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ResumeMatchResults");
                });
#pragma warning restore 612, 618
        }
    }
}
